nodeLinker: node-modules

#npmRegistries:
#    "https://npm.pkg.github.com":
#        npmAlwaysAuth: true
#    "https://registry.npmjs.org":
#        npmAlwaysAuth: true

npmScopes:
    "qinetik":
        npmAlwaysAuth: true

npmPublishRegistry: "https://npm.pkg.github.com"